" _vimrc for Windows

highlight WhitespaceEOL ctermbg=Gray guibg=Gray
match WhitespaceEOL /\s\+$/

set fileencodings=ucs-bom,utf-8,default,latin1
set fileformats=dos,unix
set guifont=Menlo:h16
set nobackup
set nomore
set noswapfile
set nu
set paste
set textwidth=0
